# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'connection.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_win_connection(object):
    def setupUi(self, win_connection):
        win_connection.setObjectName("win_connection")
        win_connection.resize(800, 480)
        win_connection.setMinimumSize(QtCore.QSize(800, 480))
        win_connection.setMaximumSize(QtCore.QSize(800, 480))

        font = QtGui.QFont()
        font.setFamily("Cafe24 Simplehae")
        font.setKerning(True)
        win_connection.setFont(font)
        win_connection.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))

        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../other/logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        win_connection.setWindowIcon(icon)

        win_connection.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        win_connection.setTabShape(QtWidgets.QTabWidget.Rounded)

        self.centralwidget = QtWidgets.QWidget(win_connection)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_QR = QtWidgets.QPushButton(self.centralwidget)
        self.btn_QR.setGeometry(QtCore.QRect(300, 280, 200, 60))

        font = QtGui.QFont()
        font.setFamily("Cafe24 Simplehae")
        font.setPointSize(18)
        font.setKerning(True)
        self.btn_QR.setFont(font)
        
        self.btn_QR.setObjectName("btn_QR")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(210, 100, 380, 135))

        font = QtGui.QFont()
        font.setFamily("Cafe24 Simplehae")
        font.setPointSize(14)
        font.setKerning(True)
        self.label.setFont(font)        
        self.label.setObjectName("label")
        
        win_connection.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(win_connection)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        win_connection.setMenuBar(self.menubar)

        self.retranslateUi(win_connection)
        QtCore.QMetaObject.connectSlotsByName(win_connection)

    def retranslateUi(self, win_connection):
        _translate = QtCore.QCoreApplication.translate
        win_connection.setWindowTitle(_translate("win_connection", "Access sys"))
        self.btn_QR.setText(_translate("win_connection", "출입"))
        self.label.setText(_translate("win_connection", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt;\">IDNTT GUARD에 오신것을 환영합니다</span></p><p align=\"center\"><span style=\" font-size:18pt;\">출입을 위해 아래 버튼을 눌러주세요</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    win_connection = QtWidgets.QMainWindow()
    ui = Ui_win_connection()
    ui.setupUi(win_connection)
    win_connection.show()
    sys.exit(app.exec_())
