# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'faceid.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_win_faceid(object):
    def setupUi(self, win_faceid):
        win_faceid.setObjectName("win_faceid")
        win_faceid.resize(800, 480)
        win_faceid.setMinimumSize(QtCore.QSize(800, 480))
        win_faceid.setMaximumSize(QtCore.QSize(800, 480))

        font = QtGui.QFont()
        font.setFamily("Cafe24 Simplehae")
        win_faceid.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../other/logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        win_faceid.setWindowIcon(icon)

        self.centralwidget = QtWidgets.QWidget(win_faceid)
        self.centralwidget.setObjectName("centralwidget")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(90, 20, 620, 350))
        self.graphicsView.setObjectName("graphicsView")

        # pushbutton == comparebutton
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(300, 390, 200, 60))

        font = QtGui.QFont()
        font.setFamily("Cafe24 Simplehae")
        font.setPointSize(18)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")

        win_faceid.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(win_faceid)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        win_faceid.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(win_faceid)
        self.statusbar.setObjectName("statusbar")
        win_faceid.setStatusBar(self.statusbar)

        self.retranslateUi(win_faceid)
        QtCore.QMetaObject.connectSlotsByName(win_faceid)

    def retranslateUi(self, win_faceid):
        _translate = QtCore.QCoreApplication.translate
        win_faceid.setWindowTitle(_translate("win_faceid", "FaceID sys"))
        self.pushButton.setText(_translate("win_faceid", "Face ID"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    win_faceid = QtWidgets.QMainWindow()
    ui = Ui_win_faceid()
    ui.setupUi(win_faceid)
    win_faceid.show()
    sys.exit(app.exec_())
