# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qr.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_win_qr(object):
    def setupUi(self, win_qr):
        win_qr.setObjectName("win_qr")
        win_qr.resize(800, 480)
        win_qr.setMinimumSize(QtCore.QSize(800, 480))
        win_qr.setMaximumSize(QtCore.QSize(800, 480))
        font = QtGui.QFont()
        font.setFamily("Cafe24 Simplehae")
        win_qr.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../other/logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        win_qr.setWindowIcon(icon)

        self.centralwidget = QtWidgets.QWidget(win_qr)
        self.centralwidget.setObjectName("centralwidget")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(90, 20, 620, 350))
        self.graphicsView.setObjectName("graphicsView")

        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(300, 390, 200, 60))
        font = QtGui.QFont()
        font.setFamily("Cafe24 Simplehae")
        font.setPointSize(18)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        
        win_qr.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(win_qr)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        win_qr.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(win_qr)
        self.statusbar.setObjectName("statusbar")
        win_qr.setStatusBar(self.statusbar)

        self.retranslateUi(win_qr)
        QtCore.QMetaObject.connectSlotsByName(win_qr)

    def retranslateUi(self, win_qr):
        _translate = QtCore.QCoreApplication.translate
        win_qr.setWindowTitle(_translate("win_qr", "QRCode sys"))
        self.pushButton.setText(_translate("win_qr", "QR CODE"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    win_qr = QtWidgets.QMainWindow()
    ui = Ui_win_qr()
    ui.setupUi(win_qr)
    win_qr.show()
    sys.exit(app.exec_())
